export const top100 = [
    {
        name: 'Carlos Toxtli',
        login: 'toxtli',
        location: 'United States , Mexico, Canada',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/1299233?s=400&v=4',
        followers: 1100,
        organizations: ['BotExperts'],
        contributions: 28287,
    },
    {
        name: 'Brian Chan',
        login: 'brianchandotcom',
        location: 'Los Angeles, CA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/282080?s=400&v=4',
        followers: 1200,
        organizations: ['liferay'],
        contributions: 21085,
    },
    {
        name: 'Fabien Potencier',
        login: 'fabpot',
        location: 'San Francisco',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/47313?s=400&v=4',
        followers: 7700,
        organizations: [
            'swiftmailer',
            'sensio',
            'symfony',
            'doctrine',
            'sensiolabs',
            'silexphp',
            'FriendsOfPHP',
            'blackfireio',
        ],
        contributions: 12947,
    },
    {
        name: 'Andrew Nesbitt',
        login: 'andrew',
        location: 'Somerset, UK',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/1060?s=400&v=4',
        followers: 1500,
        organizations: [
            'sass',
            'Homebrew',
            'railsgirls',
            'nodecopter',
            'CodeMontageHQ',
            'lnug',
            'railsgirlslondon',
            'tableflip',
            'hubot-scripts',
            'sushijs',
            'dawgs',
            'EpicGames',
            'Makerland',
            'github-beta',
            '24pullrequests',
            'SICPDistilled',
            'bathruby',
            'PubHack',
            'osscommunity',
            'librariesio',
            'splitrb',
            'dependencyci',
            'sustainers',
            'octobox',
            'ossfriday',
        ],
        contributions: 10188,
    },
    {
        name: 'Taylor Otwell',
        login: 'taylorotwell',
        location: 'Little Rock, AR',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/463230?s=400&v=4',
        followers: 11000,
        organizations: ['laravel', 'illuminate'],
        contributions: 8376,
    },
    {
        name: 'EGOIST',
        login: 'egoist',
        location: 'Chengdu, China',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/8784712?s=400&v=4',
        followers: 2400,
        organizations: ['LightBulb', 'BangumiMoe', 'saojs'],
        contributions: 7688,
    },
    {
        name: 'Hugo Giraudel',
        login: 'HugoGiraudel',
        location: 'Berlin',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/1889710?s=400&v=4',
        followers: 1700,
        organizations: ['4ae9b8', 'SassDoc'],
        contributions: 7658,
    },
    {
        name: 'Thibault Duplessis',
        login: 'ornicar',
        location: 'Paris, France',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/140370?s=400&v=4',
        followers: 1200,
        organizations: [],
        contributions: 7341,
    },
    {
        name: 'Juho Vepsäläinen',
        login: 'bebraw',
        location: 'Vienna, Austria',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/166921?s=400&v=4',
        followers: 1100,
        organizations: ['webpack', 'antwarjs', 'survivejs', 'reactabular'],
        contributions: 6895,
    },
    {
        name: 'Nelson',
        login: 'nelsonic',
        location: 'London',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/194400?s=400&v=4',
        followers: 1100,
        organizations: [
            'tableflip',
            'nodeschool',
            'meteor-london',
            'codecov',
            'foundersandcoders',
            'dwyl',
            'ConsHack',
            'TheScienceMuseum',
            'SafeLives',
            'GitHub-Beta-Dev',
        ],
        contributions: 6501,
    },
    {
        name: 'Alex Crichton',
        login: 'alexcrichton',
        location: 'San Francisco, CA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/64996?s=400&v=4',
        followers: 1200,
        organizations: [
            'rust-lang',
            'rust-lang-nursery',
            'rust-lang-deprecated',
        ],
        contributions: 6145,
    },
    {
        name: 'jongleberry',
        login: 'jonathanong',
        location: 'Los Angeles, CA',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/643505?s=400&v=4',
        followers: 1300,
        organizations: [
            'koajs',
            'expressjs',
            'stream-utils',
            'mgmtio',
            'fs-utils',
            'thenables',
            'jshttp',
            'pillarjs',
            'jongleberry',
        ],
        contributions: 5763,
    },
    {
        name: 'Mike McNeil',
        login: 'mikermcneil',
        location: 'Austin, TX',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/618009?s=400&v=4',
        followers: 1400,
        organizations: [
            'balderdashy',
            'sailsjs',
            'sailshq',
            'expressjs',
            'pillarjs',
            'node-machine',
        ],
        contributions: 5736,
    },
    {
        name: 'Ben Balter',
        login: 'benbalter',
        location: 'Washington, DC',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/282759?s=400&v=4',
        followers: 5500,
        organizations: [
            'github',
            'presidential-innovation-fellows',
            'unitedstates',
            'government',
            'cartographers-for-social-equality',
            'Digital44',
        ],
        contributions: 5699,
    },
    {
        name: 'Brent Jackson',
        login: 'jxnblk',
        location: 'New York City',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/3451712?s=400&v=4',
        followers: 2100,
        organizations: ['cssstats', 'basscss', 'c8r'],
        contributions: 5601,
    },
    {
        name: 'Yegor Bugayenko',
        login: 'yegor256',
        location: 'Palo Alto, CA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/526301?s=400&v=4',
        followers: 1400,
        organizations: ['jcabi', 'teamed', 'zerocracy'],
        contributions: 5566,
    },
    {
        name: 'Orta',
        login: 'orta',
        location: 'NYC / Huddersfield',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/49038?s=400&v=4',
        followers: 2000,
        organizations: [
            'artsy',
            'CocoaPods',
            'PutioKit',
            'NSManchester',
            'objcio',
            'specta',
            'pod5',
            'osscommunity',
            'librariesio',
            'Moya',
            'RubyNative',
            'RxSwiftCommunity',
            'danger',
            'SwiftJava',
            'playgroundbooks',
            'storybooks',
            'jest-community',
            'tsnyc',
        ],
        contributions: 5453,
    },
    {
        name: 'Rico Sta. Cruz',
        login: 'rstacruz',
        location: 'Manila, Philippines',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/74385?s=400&v=4',
        followers: 3200,
        organizations: [
            'nadarei',
            'mashupgarage',
            'js2coffee',
            'mina-deploy',
            'styledown',
            'visionmedia',
            'pnpm',
        ],
        contributions: 5313,
    },
    {
        name: 'Graham Campbell',
        login: 'GrahamCampbell',
        location: 'The United Kingdom',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/2829600?s=400&v=4',
        followers: 3500,
        organizations: [
            'thephpleague',
            'laravel',
            'bugsnag',
            'phpseclib',
            'github-beta',
            'php-build',
            'starbs',
            'HippoPHP',
            'CachetHQ',
            'StyleCI',
            'GrahamForks',
            'BootstrapCMS',
            'NotifyMeHQ',
            'ClassPreloader',
            'laravel-auto-presenter',
            'AltThree',
            'AcclimateContainer',
            'YorkCS2016',
            'MemeTrash',
            'Bottr-js',
            'CodeYork',
            'MemeSQL',
        ],
        contributions: 5135,
    },
    {
        name: '偏右',
        login: 'afc163',
        location: 'Hangzhou, China',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/507615?s=400&v=4',
        followers: 1700,
        organizations: [
            'seajs',
            'aralejs',
            'spmjs',
            'aliceui',
            'react-component',
        ],
        contributions: 5069,
    },
    {
        name: 'Kamran Ahmed',
        login: 'kamranahmedse',
        location: 'Dubai',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/4921183?s=400&v=4',
        followers: 2600,
        organizations: [],
        contributions: 4994,
    },
    {
        name: 'Josh Abernathy',
        login: 'joshaber',
        location: 'The Gem City',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/13760?s=400&v=4',
        followers: 1600,
        organizations: [
            'github',
            'libgit2',
            'ReactiveCocoa',
            'specta',
            'desktop',
        ],
        contributions: 4941,
    },
    {
        name: 'Brandon Keepers',
        login: 'bkeepers',
        location: '',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/173?s=400&v=4',
        followers: 1200,
        organizations: [
            'github',
            'hubot-scripts',
            'todogroup',
            'hubotio',
            'maintainers',
            'probot',
            'opensourceguide',
        ],
        contributions: 4873,
    },
    {
        name: 'Kenneth Reitz',
        login: 'kennethreitz',
        location: 'Winchester, VA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/119893?s=400&v=4',
        followers: 18300,
        organizations: [
            'dcpython',
            'ArchiveTeam',
            'diveintomark',
            'WhiteHouse',
            'kennethreitz-archive',
            'requests',
        ],
        contributions: 4873,
    },
    {
        name: 'Katrina Owen',
        login: 'kytrinyx',
        location: '',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/276834?s=400&v=4',
        followers: 2400,
        organizations: [
            'sinatra',
            'github',
            'exercism',
            'maintainers',
            'glitzes',
        ],
        contributions: 4866,
    },
    {
        name: 'Samuel Reed',
        login: 'STRML',
        location: 'Milwaukee, WI',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/1197375?s=400&v=4',
        followers: 1700,
        organizations: ['SublimeLinter', 'strongloop'],
        contributions: 4855,
    },
    {
        name: 'Corey Donohoe',
        login: 'atmos',
        location: 'South Lake Tahoe',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/38?s=400&v=4',
        followers: 1100,
        organizations: [],
        contributions: 4826,
    },
    {
        name: "Matthew Weier O'Phinney",
        login: 'weierophinney',
        location: 'Sioux Falls, SD, USA',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/25943?s=400&v=4',
        followers: 2000,
        organizations: ['zendframework', 'ZF-Commons', 'zendtech', 'zfcampus'],
        contributions: 4820,
    },
    {
        name: 'Yichun Zhang',
        login: 'agentzh',
        location: 'San Francisco Bay Area',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/56241?s=400&v=4',
        followers: 7400,
        organizations: ['PerlChina', 'taobao', 'alibaba', 'openresty'],
        contributions: 4740,
    },
    {
        name: 'Peter Steinberger',
        login: 'steipete',
        location: 'Vienna, Austria',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/58493?s=400&v=4',
        followers: 3400,
        organizations: ['PSPDFKit', 'Publiss', 'ResearchKit'],
        contributions: 4694,
    },
    {
        name: 'Andrey Sitnik',
        login: 'ai',
        location: 'Saint Petersburg, Russia',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/19343?s=400&v=4',
        followers: 2000,
        organizations: [
            'evilmartians',
            'gmate',
            'evolu',
            'postcss',
            'logux',
            'styletools',
        ],
        contributions: 4664,
    },
    {
        name: 'Mike Penz',
        login: 'mikepenz',
        location: 'Linz, Austria',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/1476232?s=400&v=4',
        followers: 2900,
        organizations: ['lanoraio', 'wallsplash', 'gitskarios'],
        contributions: 4659,
    },
    {
        name: 'Vincent Driessen',
        login: 'nvie',
        location: 'Netherlands',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/83844?s=400&v=4',
        followers: 1800,
        organizations: ['3rdcloud', 'jazzband'],
        contributions: 4609,
    },
    {
        name: 'Hadley Wickham',
        login: 'hadley',
        location: 'Houston, TX',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/4196?s=400&v=4',
        followers: 11500,
        organizations: [
            'ggobi',
            'rstudio',
            'rstats',
            'ropensci',
            'rjournal',
            'r-dbi',
            'RConsortium',
            'tidyverse',
            'r-lib',
        ],
        contributions: 4607,
    },
    {
        name: 'Bo-Yi Wu',
        login: 'appleboy',
        location: 'Hsinchu, Taiwan',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/21979?s=400&v=4',
        followers: 1400,
        organizations: [
            'COSCUP',
            'nodejs-tw',
            'moztw',
            'h5bp',
            'CodeIgniter-TW',
            'drone',
            'Getmore',
            'golangtw',
            'laravel-taiwan',
            'gin-gonic',
            'PHPConf-TW',
            'Mediatek-Cloud',
            'nodejs',
            'SJFinder',
            'drone-plugins',
            'go-gitea',
            'laradock',
            'gin-contrib',
            'tagfans',
            'maintainers',
            'go-training',
            'go-ggz',
        ],
        contributions: 4592,
    },
    {
        name: 'Rich Harris',
        login: 'Rich-Harris',
        location: 'NYC',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/1162160?s=400&v=4',
        followers: 1300,
        organizations: ['ractivejs', 'sveltejs'],
        contributions: 4580,
    },
    {
        name: 'Dr Nic Williams',
        login: 'drnic',
        location: 'Brisbane, Australia',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/108?s=400&v=4',
        followers: 1500,
        organizations: [
            'mocra',
            'cloudfoundry',
            'starkandwayne',
            'cloudfoundry-community',
            'logsearch',
            'dingotiles',
        ],
        contributions: 4570,
    },
    {
        name: 'Rafael França',
        login: 'rafaelfranca',
        location: 'Ottawa, ON',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/47848?s=400&v=4',
        followers: 1600,
        organizations: ['rails', 'Shopify', 'boxen'],
        contributions: 4556,
    },
    {
        name: 'Marco Pivetta',
        login: 'Ocramius',
        location: 'Frankfurt am Main',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/154256?s=400&v=4',
        followers: 2200,
        organizations: [
            'doctrine',
            'zendframework',
            'zf-fr',
            'Roave',
            'coderwall-24PullRequestsParticipant',
            'coderwall-24PullRequestsContinuous',
            'Room-11',
            'container-interop',
            'PhpFriendsOfDdd',
            'ShittySoft',
            'phptal',
            'psr7-sessions',
        ],
        contributions: 4553,
    },
    {
        name: 'Mitchell Hashimoto',
        login: 'mitchellh',
        location: 'Los Angeles, CA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/1299?s=400&v=4',
        followers: 5400,
        organizations: ['hashicorp', 'ircrelay'],
        contributions: 4541,
    },
    {
        name: 'Christophe Coevoet',
        login: 'stof',
        location: 'Paris',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/439401?s=400&v=4',
        followers: 1400,
        organizations: [
            'symfony',
            'doctrine',
            'phpspec',
            'Yrch',
            'FriendsOfSymfony',
            'Behat',
            'Incenteev',
            'Cilex',
            'minkphp',
            'Stampie',
        ],
        contributions: 4521,
    },
    {
        name: 'Igor Minar',
        login: 'IgorMinar',
        location: 'SF Bay Area, CA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/216296?s=400&v=4',
        followers: 2400,
        organizations: ['angular'],
        contributions: 4516,
    },
    {
        name: 'Phodal Huang',
        login: 'phodal',
        location: 'Shenzhen, China',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/472311?s=400&v=4',
        followers: 10200,
        organizations: ['GrowthStudio', 'wandianshenme'],
        contributions: 4496,
    },
    {
        name: 'John Wiegley',
        login: 'jwiegley',
        location: 'California, USA',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/8460?s=400&v=4',
        followers: 1100,
        organizations: ['ledger', 'lens'],
        contributions: 4475,
    },
    {
        name: 'Jeff Geerling',
        login: 'geerlingguy',
        location: 'St. Louis, MO',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/481677?s=400&v=4',
        followers: 2000,
        organizations: ['flocknote', 'acquia-pso', 'opensourcecatholic'],
        contributions: 4443,
    },
    {
        name: 'David Cramer',
        login: 'dcramer',
        location: 'San Francisco, CA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/23610?s=400&v=4',
        followers: 1800,
        organizations: ['getsentry'],
        contributions: 4435,
    },
    {
        name: 'Sebastian Bergmann',
        login: 'sebastianbergmann',
        location: 'Siegburg, Germany',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/25218?s=400&v=4',
        followers: 4000,
        organizations: ['thePHPcc', 'phar-io'],
        contributions: 4390,
    },
    {
        name: 'Bruno Volpato',
        login: 'brunocvcunha',
        location: 'Worldwide',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/3207647?s=400&v=4',
        followers: 1800,
        organizations: ['github-beta'],
        contributions: 4329,
    },
    {
        name: 'Jordan Harband',
        login: 'ljharb',
        location: 'San Mateo, CA',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/45469?s=400&v=4',
        followers: 1600,
        organizations: [
            'dreamerslab',
            'oftn-oswg',
            'airbnb',
            'tc39',
            'coderwall-charity',
            'coderwall-cub',
            'coderwall-forked',
            'es-shims',
            'js-irc',
            'MinistryOfGIFs',
            'tapjs',
        ],
        contributions: 4277,
    },
    {
        name: 'John-David Dalton',
        login: 'jdalton',
        location: '',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/4303?s=400&v=4',
        followers: 2900,
        organizations: [
            'jquery',
            'w3c',
            'bestiejs',
            'tc39',
            'lodash',
            'Microsoft',
            'MicrosoftEdge',
            'maintainers',
            'standard-things',
        ],
        contributions: 4139,
    },
    {
        name: 'Chris Sevilleja',
        login: 'sevilayha',
        location: 'Las Vegas',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/1857851?s=400&v=4',
        followers: 1300,
        organizations: ['scotch-io'],
        contributions: 4122,
    },
    {
        name: 'Paul Miller',
        login: 'paulmillr',
        location: 'Worldwide',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/574696?s=400&v=4',
        followers: 1700,
        organizations: [
            'brunch',
            'chaplinjs',
            'floatschedule',
            'es-shims',
            'hellyeahllc',
            'maintainers',
            'livescript',
            'micromatch',
        ],
        contributions: 4061,
    },
    {
        name: 'Aman Gupta',
        login: 'tmm1',
        location: 'San Francisco, CA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/2567?s=400&v=4',
        followers: 2000,
        organizations: ['rubinius', 'postrank-labs', 'graphite-project'],
        contributions: 4046,
    },
    {
        name: 'Yo-An Lin',
        login: 'c9s',
        location: 'Taipei, Taiwan',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/50894?s=400&v=4',
        followers: 1500,
        organizations: [
            'perltaiwan',
            'golangtw',
            'g0v',
            'phpbrew',
            'CIDroid',
            'phpsgi',
            'LinkerNetworks',
            'maghead',
        ],
        contributions: 3980,
    },
    {
        name: 'Cheng Zhao',
        login: 'zcbenz',
        location: 'Tokyo, Japan / China',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/639601?s=400&v=4',
        followers: 4300,
        organizations: ['github', 'atom', 'seu', 'brightray', 'Squirrel'],
        contributions: 3899,
    },
    {
        name: 'Zach Holman',
        login: 'holman',
        location: 'San Francisco',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/2723?s=400&v=4',
        followers: 5300,
        organizations: ['libgit2', 'play'],
        contributions: 3891,
    },
    {
        name: 'Kevin Sawicki',
        login: 'kevinsawicki',
        location: 'Portland, OR',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/671378?s=400&v=4',
        followers: 4000,
        organizations: [
            'github',
            'libgit2',
            'atom',
            'play',
            'sports',
            'AtomLinter',
            'electron-archive',
        ],
        contributions: 3830,
    },
    {
        name: 'Yihui Xie',
        login: 'yihui',
        location: 'Omaha, NE',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/163582?s=400&v=4',
        followers: 4000,
        organizations: ['ggobi', 'rstudio', 'cosname', 'rbind'],
        contributions: 3748,
    },
    {
        name: 'Bucky Roberts',
        login: 'buckyroberts',
        location: 'Pasadena, CA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/8547538?s=400&v=4',
        followers: 13500,
        organizations: [
            'LearnTeachCode',
            'thenewboston-developers',
            'LH-Ventures',
        ],
        contributions: 3719,
    },
    {
        name: 'Kabir Shah',
        login: 'kbrsh',
        location: '',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/15644571?s=400&v=4',
        followers: 1000,
        organizations: [],
        contributions: 3716,
    },
    {
        name: 'David J. Malan',
        login: 'dmalan',
        location: 'Cambridge, MA, USA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/788678?s=400&v=4',
        followers: 1700,
        organizations: ['cs50', 'submit50', 'check50', 'vault50'],
        contributions: 3704,
    },
    {
        name: 'Miško Hevery',
        login: 'mhevery',
        location: '',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/111951?s=400&v=4',
        followers: 3200,
        organizations: ['angular'],
        contributions: 3649,
    },
    {
        name: 'Minko Gechev',
        login: 'mgechev',
        location: 'California, USA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/455023?s=400&v=4',
        followers: 3600,
        organizations: [
            'angular',
            'beerjs',
            'FMIjs',
            'SofiaJavaScript',
            'maintainers',
        ],
        contributions: 3621,
    },
    {
        name: 'Kyle Fuller',
        login: 'kylef',
        location: 'London, England',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/44164?s=400&v=4',
        followers: 1500,
        organizations: [
            'braintree',
            'znc',
            'venmo',
            'apiaryio',
            'AFNetworking',
            'darkscience',
            'Palaver',
            'getpelican',
            'ircrelay',
            'rreply',
            'oracle',
            'cocodelabs',
            'rails-girls-summer-of-code',
            'NSLondon',
            'antitypical',
            'NSSnow',
            'Mantle',
            'the-hypermedia-project',
            'CocoaPods-Fonts',
            'QueryKit',
            'GitSubmodules',
            'SwiftOnSails',
            'rivrproject',
            'refractproject',
            'nestproject',
        ],
        contributions: 3523,
    },
    {
        name: 'Christopher Jeffrey (JJ)',
        login: 'chjj',
        location: 'San Francisco',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/470564?s=400&v=4',
        followers: 1600,
        organizations: [
            'Purse',
            'Level',
            'slap-editor',
            'winstonjs',
            'bcoin-org',
            'tothemoon-org',
        ],
        contributions: 3522,
    },
    {
        name: 'Ayende Rahien',
        login: 'ayende',
        location: 'Israel',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/116915?s=400&v=4',
        followers: 1600,
        organizations: ['ravendb', 'hibernating-rhinos'],
        contributions: 3444,
    },
    {
        name: 'Matteo Collina',
        login: 'mcollina',
        location: 'In the clouds above Italy',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/52195?s=400&v=4',
        followers: 1800,
        organizations: [
            'nearform',
            'Level',
            'nodejs',
            'mqttjs',
            'pinojs',
            'fastify',
            'upringjs',
        ],
        contributions: 3385,
    },
    {
        name: 'Mark Otto',
        login: 'mdo',
        location: 'San Francisco, CA',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/98681?s=400&v=4',
        followers: 15600,
        organizations: ['github', 'colossal', 'twbs', 'primer'],
        contributions: 3367,
    },
    {
        name: 'Yoshua Wuyts',
        login: 'yoshuawuyts',
        location: 'Berlin, Germany',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/2467194?s=400&v=4',
        followers: 1400,
        organizations: [
            'beerjs',
            'koajs',
            'nodeschool',
            'browserify',
            'stackgl',
            'datproject',
            'sitepoint-editors',
            'npm-dom',
            'github-beta',
            'township',
            'node-forward',
            'scijs',
            'stackcss',
            'nodejs',
            'man-n',
            'lazurite-app',
            'threads-js',
            'pull-stream',
            'datprotocol',
            'maintainers',
            'shipharbor',
            'standard',
            'choojs',
            'stackhtml',
        ],
        contributions: 3319,
    },
    {
        name: 'Mu-An ✌️ Chiou',
        login: 'muan',
        location: 'Taipei, Taiwan',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/1153134?s=400&v=4',
        followers: 7200,
        organizations: [
            'github',
            'atom',
            'g0v',
            'zeczec',
            'hackfoldr',
            'railsgirlslondon',
            'government',
            'nodeschool',
            'anntw',
            'education',
            'primer',
            'lab-squirrel',
            'fishtank',
            '24pullrequests',
        ],
        contributions: 3309,
    },
    {
        name: 'Kent C. Dodds',
        login: 'kentcdodds',
        location: 'Salt Lake City, Utah, USA',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/1500684?s=400&v=4',
        followers: 3500,
        organizations: [
            'angular',
            'paypal',
            'tc39',
            'webpack',
            'expressjs',
            'gdgutah',
            'github-beta',
            'airpair',
            'SLC-JS-Learners',
            'formly-js',
            'AngularAir',
            'babel',
            'ReactWeek',
            'forms-js',
            'AngularClass',
            'commitizen',
            'istanbuljs',
            'angular-todo-mvc',
            'eggheadio-github',
            'javascriptair',
            'conventional-changelog',
            'styled-components',
            'maintainers',
            'prettier',
            'babel-utils',
        ],
        contributions: 3284,
    },
    {
        name: 'Jon Skeet',
        login: 'jskeet',
        location: 'London, UK',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/17011?s=400&v=4',
        followers: 2700,
        organizations: ['google', 'GoogleCloudPlatform', 'nodatime'],
        contributions: 3273,
    },
    {
        name: 'Armin Ronacher',
        login: 'mitsuhiko',
        location: 'Austria',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/7396?s=400&v=4',
        followers: 10000,
        organizations: [
            'getsentry',
            'fireteam',
            'core',
            'python-babel',
            'lektor',
            'pallets',
            'maintainers',
        ],
        contributions: 3253,
    },
    {
        name: 'Steve Klabnik',
        login: 'steveklabnik',
        location: 'Brooklyn',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/27786?s=400&v=4',
        followers: 3300,
        organizations: [
            'rails',
            'sinatra',
            'xomboverlord',
            'shoes',
            'hacketyhack',
            'rubinius',
            'osgcc',
            'arcturo',
            'JumpstartLab',
            'documenting-ruby',
            'Farmhouse',
            'drapergem',
            'resque',
            'rust-lang-nursery',
        ],
        contributions: 3240,
    },
    {
        name: 'Henry Zhu',
        login: 'hzoo',
        location: 'ATL -> NYC',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/588473?s=400&v=4',
        followers: 1800,
        organizations: [
            'behance',
            'eslint',
            'jscs-dev',
            'babel',
            'cst',
            'lerna',
            'babel-utils',
        ],
        contributions: 3188,
    },
    {
        name: 'Justin Palmer',
        login: 'Caged',
        location: 'Portland, OR',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/25?s=400&v=4',
        followers: 1600,
        organizations: ['github', 'atom', 'sports', 'government'],
        contributions: 3179,
    },
    {
        name: 'Daniel Lew',
        login: 'dlew',
        location: 'Minneapolis',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/514850?s=400&v=4',
        followers: 2100,
        organizations: [],
        contributions: 3157,
    },
    {
        name: 'risk danger olson',
        login: 'technoweenie',
        location: 'Louisville, CO',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/21?s=400&v=4',
        followers: 2400,
        organizations: ['github', 'libgit2', 'lostisland', 'git-lfs'],
        contributions: 3156,
    },
    {
        name: 'Dan Abramov',
        login: 'gaearon',
        location: 'London, UK',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/810438?s=400&v=4',
        followers: 22600,
        organizations: [
            'facebook',
            'stampsy',
            'reactjs',
            'cssinjs',
            'babel',
            'styled-components',
            'react-dnd',
        ],
        contributions: 3155,
    },
    {
        name: 'Soumith Chintala',
        login: 'soumith',
        location: 'New York, USA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/1310570?s=400&v=4',
        followers: 4300,
        organizations: ['facebook', 'torch', 'facebookresearch', 'pytorch'],
        contributions: 3144,
    },
    {
        name: 'Feross Aboukhadijeh',
        login: 'feross',
        location: 'Mountain View, CA',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/121766?s=400&v=4',
        followers: 6500,
        organizations: [
            'PeerCDN',
            'nodeschool',
            'webtorrent',
            'browserify',
            'LXJS',
            'node-forward',
            'jsfest',
            'nodejs',
            'webrtcftw',
            'moose-team',
            'chromiumify',
            'NodeConf-EU',
            'nice-registry',
            'maintainers',
            'standard',
        ],
        contributions: 3130,
    },
    {
        name: 'Michał Budzyński',
        login: 'michalbe',
        location: 'Warsaw, Poland',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/347657?s=400&v=4',
        followers: 1200,
        organizations: [
            'nko',
            'nko2',
            'mozilla-b2g',
            'Blysk',
            'nko3',
            'VDLabs',
            'spacedock-io',
            'onGameStart',
            'Hodutu',
            'jelocartel',
            'piesku',
        ],
        contributions: 3103,
    },
    {
        name: 'Brian LeRoux',
        login: 'brianleroux',
        location: 'San Francisco, USA || Vancouver, Canada',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/990?s=400&v=4',
        followers: 1200,
        organizations: ['nitobi', 'phonegap', 'xui', 'cordova', 'smallwins'],
        contributions: 3102,
    },
    {
        name: 'William Durand',
        login: 'willdurand',
        location: 'Germany',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/217628?s=400&v=4',
        followers: 1100,
        organizations: [
            'FriendsOfSymfony',
            'propelorm',
            'clermontech',
            'willdurand-edu',
            'geocoder-php',
            'willdurand-slides',
            'openjournals',
            'TailorDev',
            'tailordev-commons',
            'tailordev-academy',
        ],
        contributions: 3094,
    },
    {
        name: 'Alex Lockwood',
        login: 'alexjlockwood',
        location: 'San Francisco, CA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/1380747?s=400&v=4',
        followers: 2000,
        organizations: ['cmu440'],
        contributions: 3083,
    },
    {
        name: 'Matias Niemelä',
        login: 'matsko',
        location: 'San Francisco, California',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/93018?s=400&v=4',
        followers: 1400,
        organizations: [
            'angular',
            'google',
            'yearofmoo',
            'Polymer',
            'yearofmoo-articles',
            'fullstackio',
            'airpair',
            'AngularAir',
            'GoogleDeveloperExperts',
        ],
        contributions: 3070,
    },
    {
        name: 'Stefan Penner',
        login: 'stefanpenner',
        location: 'San Jose, CA',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/1377?s=400&v=4',
        followers: 1200,
        organizations: ['innovatis', 'emberjs', 'babel', 'heimdalljs'],
        contributions: 3068,
    },
    {
        name: 'Adam Wathan',
        login: 'adamwathan',
        location: 'Ontario, Canada',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/4323180?s=400&v=4',
        followers: 1600,
        organizations: [
            'laravel',
            'fullstackradio',
            'nitpickci',
            'tailwindcss',
        ],
        contributions: 3064,
    },
    {
        name: 'Phil Haack',
        login: 'Haacked',
        location: 'Bellevue, WA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/19977?s=400&v=4',
        followers: 2400,
        organizations: ['github', 'NuGet', 'octokit'],
        contributions: 3055,
    },
    {
        name: 'Curran Kelleher',
        login: 'curran',
        location: 'Earth',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/68416?s=400&v=4',
        followers: 1100,
        organizations: ['UMLComputerGraphics'],
        contributions: 3054,
    },
    {
        name: 'Guillermo Rauch',
        login: 'rauchg',
        location: 'SF',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/13041?s=400&v=4',
        followers: 5700,
        organizations: ['mootools', 'component', 'jsconf', 'webmodules'],
        contributions: 3047,
    },
    {
        name: 'Ian Storm Taylor',
        login: 'ianstormtaylor',
        location: 'San Francisco, CA',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/311752?s=400&v=4',
        followers: 1100,
        organizations: [],
        contributions: 3042,
    },
    {
        name: 'Felix Krause',
        login: 'KrauseFx',
        location: 'San Francisco',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/869950?s=400&v=4',
        followers: 2700,
        organizations: [
            'google',
            'toursprung',
            'GoogleCloudPlatform',
            'fastlane',
            'google-fabric',
            'Themoji',
            'danger',
            'vapor',
            'tryswift',
            'FixIssue',
            'maintainers',
            'wwdc-family',
        ],
        contributions: 3002,
    },
    {
        name: 'TJ Holowaychuk',
        login: 'tj',
        location: 'Victoria, BC, Canada',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/25254?s=400&v=4',
        followers: 32299.999999999996,
        organizations: [
            'zeromq',
            'LearnBoost',
            'senchalabs',
            'component',
            'koajs',
            'slate',
            'clibs',
            'reworkcss',
            'expressjs',
            'cojs',
            'nanodb',
            'jstrace',
            'statsd',
            'gohttp',
            'visionmedia',
            'apex',
        ],
        contributions: 2933,
    },
    {
        name: 'John MacFarlane',
        login: 'jgm',
        location: 'Berkeley, CA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/3044?s=400&v=4',
        followers: 1200,
        organizations: ['markdown', 'commonmark', 'pandoc'],
        contributions: 2926,
    },
    {
        name: 'featherless',
        login: 'jverkoey',
        location: 'New York, NY',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/45670?s=400&v=4',
        followers: 1400,
        organizations: [
            'Three20',
            '7CubedProject',
            'nebulus',
            'nimbusios',
            'google',
            'featherless',
            'material-motion',
            '72hourgdc-2004-january',
            'material-components',
            'material-foundation',
        ],
        contributions: 2922,
    },
    {
        name: 'Cheng Lou',
        login: 'chenglou',
        location: 'Palo Alto, California',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/1909539?s=400&v=4',
        followers: 2400,
        organizations: ['BuckleScript'],
        contributions: 2895,
    },
    {
        name: 'Allan Jardine',
        login: 'DataTables',
        location: 'Scotland',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/278219?s=400&v=4',
        followers: 1100,
        organizations: [],
        contributions: 2894,
    },
    {
        name: 'Samy Pessé',
        login: 'SamyPesse',
        location: 'Lyon, France',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/845425?s=400&v=4',
        followers: 2100,
        organizations: ['GitbookIO', 'Reportr', 'HappyRhino', 'CodeboxIDE'],
        contributions: 2883,
    },
    {
        name: 'Michael Herman',
        login: 'mjhea0',
        location: 'Boulder',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/2018167?s=400&v=4',
        followers: 1000,
        organizations: [],
        contributions: 2856,
    },
    {
        name: 'paolo fragomeni',
        login: '0x00A',
        location: 'NYC',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/136109?s=400&v=4',
        followers: 1100,
        organizations: [
            'asyncly',
            'Level',
            'voltraco',
            'runtimejs',
            'normalize',
            'bpkg',
            'node-forward',
            'nodeuv',
            'qute',
            'electron',
        ],
        contributions: 2846,
    },
    {
        name: 'Tom MacWright',
        login: 'tmcw',
        location: 'San Francisco, CA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/32314?s=400&v=4',
        followers: 1800,
        organizations: ['documentationjs', 'simple-statistics', 'observablehq'],
        contributions: 2821,
    },
    {
        name: 'Brent Vatne',
        login: 'brentvatne',
        location: 'Vancouver, Canada',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/90494?s=400&v=4',
        followers: 2300,
        organizations: [
            'reactjs',
            'CodeCoreYVR',
            'expo',
            'rnplay',
            'react-native-community',
            'react-community',
        ],
        contributions: 2810,
    },
    {
        name: 'Taehoon Kim',
        login: 'carpedm20',
        location: '',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/3346407?s=400&v=4',
        followers: 3400,
        organizations: ['devsisters', 'HeXA-UNIST'],
        contributions: 2745,
    },
    {
        name: 'Ben Newman',
        login: 'benjamn',
        location: 'New York City',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/5750?s=400&v=4',
        followers: 1200,
        organizations: ['meteor', 'tc39', 'standard-things'],
        contributions: 2743,
    },
    {
        name: 'Monica Dinculescu',
        login: 'notwaldorf',
        location: 'Sun Funcisco ☀️',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/1369170?s=400&v=4',
        followers: 3600,
        organizations: [
            'webcomponents',
            'Polymer',
            'PolymerLabs',
            'PolymerElements',
        ],
        contributions: 2706,
    },
    {
        name: 'Tatsuhiko Miyagawa',
        login: 'miyagawa',
        location: 'San Francisco, CA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/3499?s=400&v=4',
        followers: 2100,
        organizations: ['Perl-Toolchain-Gang', 'plack'],
        contributions: 2695,
    },
    {
        name: 'Ryan Nystrom',
        login: 'rnystrom',
        location: 'New York, NY',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/739696?s=400&v=4',
        followers: 1600,
        organizations: ['Instagram'],
        contributions: 2690,
    },
    {
        name: 'Richard Davey',
        login: 'photonstorm',
        location: 'UK',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/164476?s=400&v=4',
        followers: 1400,
        organizations: [],
        contributions: 2658,
    },
    {
        name: 'mattn',
        login: 'mattn',
        location: 'Osaka, Japan',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/10111?s=400&v=4',
        followers: 3700,
        organizations: [
            'vimjolts',
            'vimpr',
            'perl-users-jp',
            'termtter',
            'ukigumo',
            'vim-jp',
            'blosxom-fanatics',
            'golang-samples',
            'golang',
            'akechi',
            'gobook2016',
            'tama-go',
        ],
        contributions: 2656,
    },
    {
        name: 'Douglas Wilson',
        login: 'dougwilson',
        location: '',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/67512?s=400&v=4',
        followers: 1700,
        organizations: [
            'koajs',
            'expressjs',
            'stream-utils',
            'repo-utils',
            'crypto-utils',
            'jshttp',
            'pillarjs',
            'nodejs',
            'salesforce-marketingcloud',
            'mysqljs',
            'ExpressGateway',
            'tsqllint',
        ],
        contributions: 2655,
    },
    {
        name: 'Jake Wharton',
        login: 'JakeWharton',
        location: 'Pittsburgh, PA, USA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/66577?s=400&v=4',
        followers: 42000,
        organizations: [
            'google',
            'robolectric',
            'ReactiveX',
            'grpc',
            'todogroup',
        ],
        contributions: 2654,
    },
    {
        name: 'Evan You',
        login: 'yyx990803',
        location: 'New Jersey / China',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/499550?s=400&v=4',
        followers: 24400,
        organizations: [],
        contributions: 2645,
    },
    {
        name: 'Krzysztof Zabłocki',
        login: 'krzysztofzablocki',
        location: 'Warsaw, Poland',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/1468993?s=400&v=4',
        followers: 2000,
        organizations: [],
        contributions: 2632,
    },
    {
        name: 'Eduardo Lundgren',
        login: 'eduardolundgren',
        location: 'California',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/113087?s=400&v=4',
        followers: 1100,
        organizations: [
            'liferay',
            'webcomponents',
            'node-gh',
            'customelements',
            'deprecate',
            'wedeploy',
            'metal',
        ],
        contributions: 2629,
    },
    {
        name: 'Christopher Chedeau',
        login: 'vjeux',
        location: 'San Francisco, California',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/197597?s=400&v=4',
        followers: 2000,
        organizations: ['jDataView'],
        contributions: 2602,
    },
    {
        name: 'Max Howell',
        login: 'mxcl',
        location: 'Savannah, GA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/58962?s=400&v=4',
        followers: 3500,
        organizations: ['Homebrew', 'PromiseKit', 'codebasesav'],
        contributions: 2586,
    },
    {
        name: 'Domenic Denicola',
        login: 'domenic',
        location: 'New York, NY',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/617481?s=400&v=4',
        followers: 2900,
        organizations: [
            'google',
            'tc39',
            'whatwg',
            'promises-aplus',
            'w3ctag',
            'npm',
            'jsdom',
            'nodejs',
            'WebAssembly',
            'test-tw',
        ],
        contributions: 2570,
    },
    {
        name: 'Alex Gaynor',
        login: 'alex',
        location: 'Washington D.C.',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/772?s=400&v=4',
        followers: 3900,
        organizations: [
            'django',
            'pypa',
            'xattr',
            'python',
            'WhiteHouse',
            'wal-e',
            'topazproject',
            'PyCon',
            'pyca',
        ],
        contributions: 2556,
    },
    {
        name: 'Mr.doob',
        login: 'mrdoob',
        location: '',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/97088?s=400&v=4',
        followers: 10200,
        organizations: ['xplsv'],
        contributions: 2555,
    },
    {
        name: 'Jose Diaz-Gonzalez',
        login: 'josegonzalez',
        location: 'New York, NY',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/65675?s=400&v=4',
        followers: 1100,
        organizations: [
            'cakephp',
            'seatgeek',
            'Homebrew',
            'OctoBear',
            'unitedstates',
            'CakeSoftwareFoundation',
            'FriendsOfCake',
            'python-diamond',
            'gliderlabs',
            'dokku',
            'python-beaver',
            'dokku-community',
        ],
        contributions: 2516,
    },
    {
        name: 'Francois Zaninotto',
        login: 'fzaninotto',
        location: 'Nancy, France',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/99944?s=400&v=4',
        followers: 1200,
        organizations: ['propelorm', 'marmelab'],
        contributions: 2507,
    },
    {
        name: 'Yi Shen',
        login: 'pissang',
        location: 'Shanghai, China',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/841551?s=400&v=4',
        followers: 1100,
        organizations: [],
        contributions: 2472,
    },
    {
        name: 'James Montemagno',
        login: 'jamesmontemagno',
        location: 'Seattle, WA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/1676321?s=400&v=4',
        followers: 2700,
        organizations: ['planetxamarin'],
        contributions: 2427,
    },
    {
        name: 'Paul Betts',
        login: 'paulcbetts',
        location: 'San Francisco',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/1396?s=400&v=4',
        followers: 1500,
        organizations: [
            'ProgRx',
            'play',
            'reactiveui',
            'octokit',
            'Squirrel',
            'akavache',
            'flight-labs',
        ],
        contributions: 2414,
    },
    {
        name: 'Paul Irish',
        login: 'paulirish',
        location: 'Palo Alto',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/39191?s=400&v=4',
        followers: 24900,
        organizations: [
            'jquery',
            'Modernizr',
            'sass',
            'diveintomark',
            'h5bp',
            'jshint',
            'google',
            'ot-crew',
            'robohornet',
            'yeoman',
            'GoogleChrome',
            'html5rocks',
            'components',
            'bower',
            'DeveloperToolsWG',
            'ChromeDevTools',
            'so-fancy',
            'yarnpkg',
        ],
        contributions: 2412,
    },
    {
        name: 'Alexander Makarov',
        login: 'samdark',
        location: 'Russia',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/47294?s=400&v=4',
        followers: 1800,
        organizations: ['yiiext', 'yiisoft'],
        contributions: 2403,
    },
    {
        name: 'Mads Kristensen',
        login: 'madskristensen',
        location: 'Redmond, WA',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/1258877?s=400&v=4',
        followers: 1600,
        organizations: ['ligershark'],
        contributions: 2394,
    },
    {
        name: 'Tobias Koppers',
        login: 'sokra',
        location: 'Germany',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/1365881?s=400&v=4',
        followers: 2700,
        organizations: [
            'webpack',
            'jmpressjs',
            'css-modules',
            'webpack-contrib',
        ],
        contributions: 2391,
    },
    {
        name: 'Marijn Haverbeke',
        login: 'marijnh',
        location: 'Berlin',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/144427?s=400&v=4',
        followers: 2600,
        organizations: [
            'recursecenter',
            'nytm',
            'OpenTechSchool',
            'codemirror',
            'ternjs',
            'ProseMirror',
        ],
        contributions: 2378,
    },
    {
        name: 'Alan Hamlett',
        login: 'alanhamlett',
        location: 'San Francisco',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/522344?s=400&v=4',
        followers: 4100,
        organizations: ['braintree', 'onlinemediagroup', 'wakatime'],
        contributions: 2377,
    },
    {
        name: 'Wes McKinney',
        login: 'wesm',
        location: 'New York, NY',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/329591?s=400&v=4',
        followers: 4300,
        organizations: [
            'apache',
            'statsmodels',
            'pydata',
            'datapad',
            'twosigma',
            'conda-forge',
            'pandas-dev',
            'maintainers',
        ],
        contributions: 2367,
    },
    {
        name: 'José Valim',
        login: 'josevalim',
        location: 'Kraków, Poland',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/9582?s=400&v=4',
        followers: 7200,
        organizations: [
            'plataformatec',
            'elixir-lang',
            'beamcommunity',
            'phoenixframework',
            'hexpm',
            'elixir-ecto',
            'elixir-plug',
        ],
        contributions: 2361,
    },
    {
        name: 'Jennifer (Jenny) Bryan',
        login: 'jennybc',
        location: 'Vancouver, BC, Canada',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/599454?s=400&v=4',
        followers: 1700,
        organizations: [
            'rstudio',
            'ropensci',
            'swcarpentry',
            'datacarpentry',
            'STAT545-UBC',
            'Reproducible-Science-Curriculum',
            'STAT540-UBC',
            'UBC-MDS',
            'ropenscilabs',
            'forwards',
            'rsheets',
            'tidyverse',
            'r-lib',
        ],
        contributions: 2361,
    },
    {
        name: 'Andrew Gallant',
        login: 'BurntSushi',
        location: 'Marlborough, MA',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/456674?s=400&v=4',
        followers: 1300,
        organizations: [
            'diffeo',
            'docopt',
            'rust-lang',
            'toml-lang',
            'rust-lang-nursery',
        ],
        contributions: 2348,
    },
    {
        name: 'Zeno Rocha',
        login: 'zenorocha',
        location: 'California',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/398893?s=400&v=4',
        followers: 5400,
        organizations: [
            'liferay',
            'h5bp',
            'yeoman',
            'braziljs',
            'webcomponents',
            'jquery-boilerplate',
            'customelements',
            'GoogleDeveloperExperts',
            'devspace',
        ],
        contributions: 2341,
    },
    {
        name: 'contra',
        login: 'contra',
        location: 'New York, NY',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/425716?s=400&v=4',
        followers: 2000,
        organizations: [
            'rayo',
            'wearefractal',
            'FACTORYX',
            'genomejs',
            'gulpjs',
            'hackphx-arduinowearables',
            'CodeAndBeats',
            'revisitors',
            'parks-foundation',
            'shastajs',
            'staeco',
        ],
        contributions: 2333,
    },
    {
        name: 'Jared Hanson',
        login: 'jaredhanson',
        location: 'Berkeley, CA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/10355?s=400&v=4',
        followers: 1800,
        organizations: [
            'sifteo',
            'buspreneurs',
            'sailjs',
            'passport',
            'anchorjs',
            'rivetjs',
            'auth0',
            'tensileops',
            'bixbyjs',
        ],
        contributions: 2329,
    },
    {
        name: 'Ryan Bigg',
        login: 'radar',
        location: 'Melbourne, Australia',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/2687?s=400&v=4',
        followers: 1500,
        organizations: [
            'spree',
            'redis-store',
            'activerecord-hackery',
            'goamz',
            'airpair',
        ],
        contributions: 2315,
    },
    {
        name: 'Nicolás Bevacqua',
        login: 'bevacqua',
        location: 'https://twitter.com/nzgb',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/934293?s=400&v=4',
        followers: 3400,
        organizations: [
            'foundit',
            'beerjs',
            'ponyfoo',
            'buildfirst',
            'nodeschool',
            'elastic',
            'sourceful',
            'node-forward',
            'oneshot',
            'taunus',
            'nodeconf',
            'banodejs',
            'latamjs',
            'mjavascript',
            'maintainers',
        ],
        contributions: 2310,
    },
    {
        name: 'xdf',
        login: 'xudafeng',
        location: 'China',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/1011681?s=400&v=4',
        followers: 1300,
        organizations: [
            'cnodejs',
            'alibaba',
            'node-modules',
            'saijs',
            'uestcer',
            'reliablejs',
            'react-component',
            'nodejs',
            'iscanner',
            'doing-data-science',
            'ant-design',
            'macacajs',
            'hiloteam',
            'eggjs',
            'maintainers',
        ],
        contributions: 2308,
    },
    {
        name: 'Jeremy Kun',
        login: 'j2kun',
        location: 'San Francisco, CA',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/2467754?s=400&v=4',
        followers: 1000,
        organizations: [],
        contributions: 2273,
    },
    {
        name: 'Dominic Tarr',
        login: 'dominictarr',
        location: 'New Zealand',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/259374?s=400&v=4',
        followers: 2200,
        organizations: ['ssbc', 'pull-stream'],
        contributions: 2259,
    },
    {
        name: 'Avelino',
        login: 'avelino',
        location: 'Roshamuul, Menera',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/31996?s=400&v=4',
        followers: 1600,
        organizations: [
            'django',
            'plone',
            'bottlepy',
            'MongoEngine',
            'filmow',
            'mining',
            'nuveo',
            'dut-lang',
            'prest',
            'rumlang',
        ],
        contributions: 2234,
    },
    {
        name: 'Vinta',
        login: 'vinta',
        location: 'Taipei, Taiwan',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/652070?s=400&v=4',
        followers: 2000,
        organizations: ['CodeTengu'],
        contributions: 2213,
    },
    {
        name: 'Jason Miller',
        login: 'developit',
        location: 'Hamilton, Ontario, Canada',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/105127?s=400&v=4',
        followers: 2300,
        organizations: ['preactjs-templates'],
        contributions: 2199,
    },
    {
        name: 'ashley williams',
        login: 'ashleygwilliams',
        location: 'NYC',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/1163554?s=400&v=4',
        followers: 2000,
        organizations: [
            'sinatra',
            'jquery',
            'atom',
            'csvsoundsystem',
            'rust-lang',
            'npm',
            'digitalwes',
            'endpoints',
            'nodejs',
            'rust-community',
            'intermezzOS',
            'rustbridge',
            'NodeTogether',
            'maintainers',
        ],
        contributions: 2193,
    },
    {
        name: 'Ash Furrow',
        login: 'ashfurrow',
        location: 'New York',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/498212?s=400&v=4',
        followers: 2700,
        organizations: [
            'artsy',
            'ReactiveCocoa',
            'raywenderlich',
            'NotificationCenter',
            'antitypical',
            'Quick',
            'accesscode-2-2',
            'Moya',
            'RxSwiftCommunity',
            'danger',
            'tryswift',
            'maintainers',
        ],
        contributions: 2192,
    },
    {
        name: 'Fatih Kadir Akın',
        login: 'f',
        location: 'Istanbul, Turkey',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/196477?s=400&v=4',
        followers: 1200,
        organizations: [
            'jstanbul',
            'deloreanjs',
            'vieuxio',
            'kemalcr',
            'packathon',
            'ProteinTech',
        ],
        contributions: 2178,
    },
    {
        name: 'Wei Wang',
        login: 'onevcat',
        location: 'Kawasaki, Japan/Shanghai, China',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/1019875?s=400&v=4',
        followers: 10200,
        organizations: ['objcio', 'objccn', 'swifter-tips'],
        contributions: 2166,
    },
    {
        name: 'Todd Motto',
        login: 'toddmotto',
        location: 'England, UK',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/1655968?s=400&v=4',
        followers: 5000,
        organizations: [
            'conditionizr',
            'kendo-labs',
            'fullstackio',
            'HTML5Hub',
            'html5blank',
            'learn-co-curriculum',
            'AngularAir',
            'GoogleDeveloperExperts',
            'ngmigrate',
            'UltimateAngular',
        ],
        contributions: 2153,
    },
    {
        name: 'PatrickJS [tipe.io]',
        login: 'gdi2290',
        location: 'San Francisco, CA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/1016365?s=400&v=4',
        followers: 1400,
        organizations: [
            'angular',
            'monsoonco',
            'keychain',
            'webpack',
            'hackreactor',
            'angularjs-in-action',
            'fullstackio',
            'ng-newsletter',
            'FACTORYX',
            'RedditInsight',
            'TypeStrong',
            'vue-software',
            'NodeProgram',
            'keen',
            'AngularAir',
            'ReactWeek',
            'AngularClass',
            'types',
            'storybooks',
            'ng-cruise',
            'maintainers',
            'nguniversal',
            'ngatl',
            'onespeed-io',
            'tipeio',
        ],
        contributions: 2153,
    },
    {
        name: 'Rob Eisenberg',
        login: 'EisenbergEffect',
        location: '',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/131485?s=400&v=4',
        followers: 1600,
        organizations: [
            'BlueSpire',
            'Microsoft',
            'TallyDotNet',
            'Caliburn-Micro',
            'rpgwithme',
            'aurelia',
            'durandalproject',
            'MicrosoftDocs',
            'maintainers',
        ],
        contributions: 2151,
    },
    {
        name: 'Andrew Kane',
        login: 'ankane',
        location: 'San Francisco, CA',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/220358?s=400&v=4',
        followers: 1300,
        organizations: ['instacart'],
        contributions: 2134,
    },
    {
        name: 'Keijiro Takahashi',
        login: 'keijiro',
        location: 'Japan',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/343936?s=400&v=4',
        followers: 5000,
        organizations: ['radium-software', 'unity3d-jp'],
        contributions: 2128,
    },
    {
        name: 'Vladimir Kharlampidi',
        login: 'nolimits4web',
        location: 'Rostov-on-Don, Russia',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/999588?s=400&v=4',
        followers: 1300,
        organizations: ['idangerous', 'framework7io'],
        contributions: 2127,
    },
    {
        name: 'David Fowler',
        login: 'davidfowl',
        location: 'Bellevue, WA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/95136?s=400&v=4',
        followers: 2100,
        organizations: [
            'projectkudu',
            'SignalR',
            'NuGet',
            'JabbR',
            'aspnet',
            'OmniSharp',
        ],
        contributions: 2123,
    },
    {
        name: '王爵nice',
        login: 'biezhi',
        location: 'Shanghai, China',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/3849072?s=400&v=4',
        followers: 1600,
        organizations: [
            'lets-blade',
            'junicorn',
            'JavaExamples',
            'LittleFriendsGroup',
            'V2Git',
            'apachecn',
            'otale',
            'lets-golang',
            'java-webbee',
            'kongzhongfinance',
            'dev-cheats',
        ],
        contributions: 2113,
    },
    {
        name: 'Lea Verou',
        login: 'LeaVerou',
        location: 'Boston, MA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/175836?s=400&v=4',
        followers: 10000,
        organizations: ['haystack', 'mavoweb'],
        contributions: 2110,
    },
    {
        name: 'David Miller',
        login: 'davidtmiller',
        location: 'Orlando, FL',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/8400627?s=400&v=4',
        followers: 1100,
        organizations: ['BlackrockDigital'],
        contributions: 2110,
    },
    {
        name: '',
        login: 'odersky',
        location: '',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/795990?s=400&v=4',
        followers: 1700,
        organizations: [],
        contributions: 2102,
    },
    {
        name: 'victor felder',
        login: 'vhf',
        location: 'Switzerland',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/2022803?s=400&v=4',
        followers: 2900,
        organizations: [
            'recursecenter',
            'nzzdev',
            'upfrontIO',
            'openturk',
            'zestedesavoir',
            'EbookFoundation',
            'eXascaleInfolab',
            'syntax-tree',
            'rehypejs',
        ],
        contributions: 2093,
    },
    {
        name: 'Sam Soffes',
        login: 'soffes',
        location: 'San Francisco',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/52870?s=400&v=4',
        followers: 3800,
        organizations: ['nothingmagical'],
        contributions: 2083,
    },
    {
        name: 'Max Stoiber',
        login: 'mxstbr',
        location: 'Vienna, Austria',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/7525670?s=400&v=4',
        followers: 2300,
        organizations: [
            'then',
            'keystonejs',
            'reactjs',
            'postcss',
            'elementalui',
            'reactvienna',
            'styled-components',
            'micro-analytics',
            'react-boilerplate',
            'withspectrum',
        ],
        contributions: 2048,
    },
    {
        name: '勾三股四',
        login: 'Jinjiang',
        location: 'Hangzhou, China',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/206848?s=400&v=4',
        followers: 3500,
        organizations: ['vuejs', 'amfe'],
        contributions: 2038,
    },
    {
        name: 'Peter Wang',
        login: 'happypeter',
        location: '微信：happypeter1983',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/72467?s=400&v=4',
        followers: 3300,
        organizations: ['happycasts'],
        contributions: 2023,
    },
    {
        name: 'Baohua Yang',
        login: 'yeasy',
        location: '',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/1920564?s=400&v=4',
        followers: 1300,
        organizations: ['hyperledger'],
        contributions: 2004,
    },
    {
        name: 'Mathias Buus',
        login: 'mafintosh',
        location: 'Copenhagen, Denmark',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/376661?s=400&v=4',
        followers: 3300,
        organizations: [
            'Level',
            'nodeschool',
            'datproject',
            'nodejs',
            'webrtcftw',
            'moose-team',
            'prebuild',
        ],
        contributions: 2001,
    },
    {
        name: 'Zihan Chen',
        login: 'vczh',
        location: 'Seattle, WA, USA',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/773569?s=400&v=4',
        followers: 10200,
        organizations: ['vczh-libraries'],
        contributions: 2001,
    },
    {
        name: 'Draveness',
        login: 'Draveness',
        location: 'Beijing, China',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/6493255?s=400&v=4',
        followers: 1900,
        organizations: [
            'SSSTA',
            'objccn',
            'X-Strikers',
            'Tictalkin',
            'LifeContinued',
            'ModelModel',
            'Primix',
            'LiberatorX',
            'draven-archive',
        ],
        contributions: 1963,
    },
    {
        name: 'Dustin Diaz',
        login: 'ded',
        location: 'California',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/372683?s=400&v=4',
        followers: 2000,
        organizations: ['ender-js', 'agent'],
        contributions: 1963,
    },
    {
        name: 'Vlad Filippov',
        login: 'vladikoff',
        location: 'North America',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/128755?s=400&v=4',
        followers: 1100,
        organizations: [
            'jquery',
            'mozilla',
            'mozilla-services',
            'ot-crew',
            'gruntjs',
            'nko3',
            'node-task',
            'bower',
            'nko4',
            'theintern',
            'voxel',
            'UTMQ',
            'webcompat',
            'cerealconf',
            'node-forward',
            'archon-runtime',
            'node-freight',
            'Open-Web-Conf',
            'OpenSourceSystemPodcast',
        ],
        contributions: 1958,
    },
    {
        name: 'Ben Noordhuis',
        login: 'bnoordhuis',
        location: 'The Netherlands',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/275871?s=400&v=4',
        followers: 1700,
        organizations: [
            'Jasig',
            'linuxfoundation',
            'IBM',
            'gypified',
            'strongloop',
            'libuv',
            'node-forward',
            'nodejs',
        ],
        contributions: 1954,
    },
    {
        name: 'Jen Dewalt',
        login: 'jendewalt',
        location: 'United States',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/3196668?s=400&v=4',
        followers: 2300,
        organizations: [],
        contributions: 1953,
    },
    {
        name: 'Jess Frazelle',
        login: 'jessfraz',
        location: 'PID 1',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/1445228?s=400&v=4',
        followers: 5200,
        organizations: [],
        contributions: 1952,
    },
    {
        name: 'Fedor Indutny',
        login: 'indutny',
        location: 'USA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/238531?s=400&v=4',
        followers: 2200,
        organizations: ['bem', 'libuv', 'krakenjs', 'js-js', 'nodejs'],
        contributions: 1946,
    },
    {
        name: 'Oliver Gierke',
        login: 'olivergierke',
        location: 'Dresden, Germany',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/128577?s=400&v=4',
        followers: 1600,
        organizations: [
            'spring-projects',
            'JavaPosseRoundup',
            'st-tu-dresden',
            'st-tu-dresden-praktikum',
            'SpringOnePlatform2016',
        ],
        contributions: 1936,
    },
    {
        name: '他们叫我狼叔',
        login: 'i5ting',
        location: 'china beijing',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/3118295?s=400&v=4',
        followers: 2700,
        organizations: ['moajs', 'dev-reading'],
        contributions: 1929,
    },
    {
        name: 'Wladimir J. van der Laan',
        login: 'laanwj',
        location: 'Eindhoven, The Netherlands',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/126646?s=400&v=4',
        followers: 1200,
        organizations: ['bitcoin', 'p2p', 'bitcoin-core', 'mit-dci'],
        contributions: 1912,
    },
    {
        name: 'drakeet',
        login: 'drakeet',
        location: 'Hangzhou, China',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/5214214?s=400&v=4',
        followers: 5500,
        organizations: [],
        contributions: 1911,
    },
    {
        name: 'James Kyle',
        login: 'thejameskyle',
        location: 'Sydney',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/952783?s=400&v=4',
        followers: 3200,
        organizations: [
            'cloudflare',
            'tc39',
            'marionettejs',
            'Thinkmill',
            'keystonejs',
            'babel',
            'elementalui',
            'npm-scripts',
            'lerna',
            'styled-components',
            'yarnpkg',
            'maintainers',
            'GET-TYPED',
            'babel-utils',
            'projectorjs',
            'boltpkg',
            'parcel-bundler',
        ],
        contributions: 1867,
    },
    {
        name: 'Ahmet Alp Balkan',
        login: 'ahmetb',
        location: 'Seattle, WA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/159209?s=400&v=4',
        followers: 1200,
        organizations: ['google', 'GoogleCloudPlatform', 'kubernetes'],
        contributions: 1866,
    },
    {
        name: 'Stephen Diehl',
        login: 'sdiehl',
        location: 'Boston, MA',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/236767?s=400&v=4',
        followers: 1400,
        organizations: [
            'pydata',
            'adjoint-io',
            'DataHaskell',
            'llvm-hs',
            'haskell-wasm',
        ],
        contributions: 1865,
    },
    {
        name: '小弟调调™',
        login: 'jaywcjlove',
        location: 'Shanghai, China',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/1680273?s=400&v=4',
        followers: 1100,
        organizations: ['JSLite', 'uiw-react'],
        contributions: 1859,
    },
    {
        name: 'Junio C Hamano',
        login: 'gitster',
        location: 'Mountain View, CA',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/54884?s=400&v=4',
        followers: 1400,
        organizations: ['git'],
        contributions: 1859,
    },
    {
        name: 'Daniel Spiewak',
        login: 'djspiewak',
        location: 'Boulder, CO',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/752?s=400&v=4',
        followers: 1100,
        organizations: ['precog', 'slamdata', 'quasar-analytics'],
        contributions: 1858,
    },
    {
        name: 'Simone Margaritelli',
        login: 'evilsocket',
        location: 'Rome, Italy',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/86922?s=400&v=4',
        followers: 2300,
        organizations: ['Zimperium', 'bettercap'],
        contributions: 1846,
    },
    {
        name: 'Mariotaku',
        login: 'mariotaku',
        location: 'Zhengzhou, Henan, China',
        language: '',
        gravatar: 'https://avatars1.githubusercontent.com/u/830358?s=400&v=4',
        followers: 1600,
        organizations: ['TwidereProject'],
        contributions: 1845,
    },
    {
        name: 'Kyle Robinson Young',
        login: 'shama',
        location: 'Portland, OR',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/99604?s=400&v=4',
        followers: 1300,
        organizations: [
            'croogo',
            'gruntjs',
            'webpack',
            'jmpressjs',
            'node-task',
            'nko4',
            'voxel',
            'ynab',
            'moose-team',
            'OpenSourceSystemPodcast',
            'weekend-tacos-github',
            'choojs',
        ],
        contributions: 1833,
    },
    {
        name: 'Cameron Davidson-Pilon',
        login: 'CamDavidsonPilon',
        location: 'Ottawa, Canada',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/884032?s=400&v=4',
        followers: 2000,
        organizations: ['Shopify', 'DataOrigami'],
        contributions: 1830,
    },
    {
        name: 'Dave Syer',
        login: 'dsyer',
        location: 'London',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/124075?s=400&v=4',
        followers: 1400,
        organizations: ['spring-projects', 'scratches'],
        contributions: 1813,
    },
    {
        name: 'Benjamin Winterberg',
        login: 'winterbe',
        location: 'Hanover, Germany',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/485033?s=400&v=4',
        followers: 1200,
        organizations: ['idon'],
        contributions: 1798,
    },
    {
        name: 'Denny Britz',
        login: 'dennybritz',
        location: 'Mountain View, CA',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/403133?s=400&v=4',
        followers: 4000,
        organizations: [],
        contributions: 1785,
    },
    {
        name: 'Arun Gupta',
        login: 'arun-gupta',
        location: 'San Jose, CA',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/113947?s=400&v=4',
        followers: 1700,
        organizations: ['aws', 'Adopt-a-JSR'],
        contributions: 1785,
    },
    {
        name: 'Mary Rose Cook',
        login: 'maryrosecook',
        location: 'London, UK',
        language: '',
        gravatar: 'https://avatars0.githubusercontent.com/u/2716?s=400&v=4',
        followers: 1400,
        organizations: ['recursecenter'],
        contributions: 1776,
    },
    {
        name: 'dennis zhuang',
        login: 'killme2008',
        location: 'HangZhou/SuZhou,China',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/14142?s=400&v=4',
        followers: 1200,
        organizations: [],
        contributions: 1760,
    },
    {
        name: 'Ian Lunn',
        login: 'IanLunn',
        location: 'Devon, UK',
        language: '',
        gravatar: 'https://avatars2.githubusercontent.com/u/694641?s=400&v=4',
        followers: 1400,
        organizations: [],
        contributions: 1757,
    },
    {
        name: 'Ruan YiFeng',
        login: 'ruanyf',
        location: 'Shanghai, China',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/905434?s=400&v=4',
        followers: 33900,
        organizations: [],
        contributions: 1755,
    },
    {
        name: 'Roy Binux',
        login: 'binux',
        location: 'London, UK',
        language: '',
        gravatar: 'https://avatars3.githubusercontent.com/u/646451?s=400&v=4',
        followers: 2100,
        organizations: [],
        contributions: 1745,
    },
];
